#!/bin/bash
desc=$1
test -z $desc
if [ $? -eq 0 ]; then
  echo "Usage: $0 [keyname]"
  exit 1
fi
keyid=`keyctl search @u user $desc`
echo "$keyid" | grep -q "^[0-9]*"
if test -z "$keyid"; then
  exit 1
else
  keyctl pipe $keyid
  echo
fi
